//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleInvoice()
        {
            this.SaleInvoiceDetails = new HashSet<SaleInvoiceDetail>();
        }
    
        public int SaleInvoiceId { get; set; }
        public System.DateTime Date { get; set; }
        public long InvoiceTypeId { get; set; }
        public long LocationId { get; set; }
        public long PartyId { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual InvoiceType InvoiceType { get; set; }
        public virtual Location Location { get; set; }
        public virtual Party Party { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleInvoiceDetail> SaleInvoiceDetails { get; set; }
    }
}
