//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInvoiceDetail
    {
        public long SaleInvoiceDetailId { get; set; }
        public int SaleInvoiceId { get; set; }
        public int ItemId { get; set; }
        public int Qty { get; set; }
        public decimal SalePrice { get; set; }
        public decimal Total { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual SaleInvoice SaleInvoice { get; set; }
    }
}
